### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by mahdikarimi5509** [HarshAndroid/FreeVPN-App-Flutter#1]
My configuration works in the openvpn app, but here it just shows authentication and doesn't connect

**Comment by HarshAndroid** [comment]
Are you changing username and password while connecting to your OpenVPN server because I'm using default username as 'vpn' and password as 'vpn'.

One possible reason also can be: Actually these libraries I'm using is compiled in 2020 and may be it doesn't not support latest server versions.

Suggestion: Try using once OpenVPN_flutter package, may be it can be helpful to you.
https://pub.dev/packages/openvpn_flutter

**Comment by mahdikarimi5509** [comment]
Username and password are correct.
I tried with this package and it didn't connect .
And it gets stuck in authentication.

**Comment by HarshAndroid** [comment]
Actually I also can't do much regarding some vpn's not connecting but I can share you a sample video in which I've shown connecting vpns with vpngate site and most of them works as per my testing.
Video link: https://youtu.be/jQa75IVVpoo
