### ISSUE TITLE
 Got unrecognized command>FATAL:Error: private key password verification failed

### ISSUE THREAD

**Issue by amir-hossein-rajaezadeh** [HarshAndroid/FreeVPN-App-Flutter#19]
I/OpenVPN (16206): Starting openvpn
I/openvpn (16206): Got unrecognized command>FATAL:Error: private key password verification failed
I/OpenVPN (16206): OpenVPN process exited
D/EGL_emulation(16206): app_time_stats: avg=92.87ms min=11.35ms max=2537.86ms count=33
D/EGL_emulation(16206): app_time_stats: avg=59.08ms min=1.32ms max=2381.08ms count=47
[log] Precache Interstitial Ad - Id: ca-app-pub-3940256099942544/1033173712

**Comment by HarshAndroid** [comment]
As I responded on YouTube comments:

This project will not work for you if you have a separate key, I will recommend checking the package below. There are chances that it may also not work, because it also doesn't have a direct private key parameter rather you have to merge it in config and then try (but research will be required).

https://pub.dev/packages/openvpn_flutter

And if you will take my suggestion then try using wireguard instead of OpenVPN protocol because it's more efficient and easy to setup. Also have a good package too in pub.dev.

**Comment by WANDIKAPRATAMA** [comment]
> As I responded on YouTube comments:
> 
> This project will not work for you if you have a separate key, I will recommend checking the package below. There are chances that it may also not work, because it also doesn't have a direct private key parameter rather you have to merge it in config and then try (but research will be required).
> 
> https://pub.dev/packages/openvpn_flutter
> 
> And if you will take my suggestion then try using wireguard instead of OpenVPN protocol because it's more efficient and easy to setup. Also have a good package too in pub.dev.

Hi sir, are you open to consulting about using the Open VPN Config file? , you are very competent in this matter

**Comment by HarshAndroid** [comment]
I wouldn't say I'm highly proficient in this topic, but I do my best to learn from available resources and apply what I've learned. 
There’s a possibility that I may not have the answers to some of your questions regarding Open VPN Config files as well.

**Comment by HarshAndroid** [comment]
Since there hasn’t been any recent activity on this issue, I will be closing it for now.
